version: "3.8"
services:

    blackfire:
        image: blackfire/blackfire:2
        environment:
            #BLACKFIRE_CLIENT_ID: 0d663c61-c763-43bb-8d47-37007861b702
            #BLACKFIRE_CLIENT_TOKEN: 99602804164d97075782088ef4c791e1ebd4c55bcaa27fce83c7fc1c62f376c6
            BLACKFIRE_SERVER_ID: bf0501d8-c4ff-4b49-829d-79a551449aaa
            BLACKFIRE_SERVER_TOKEN: 31547b1abf6e6601dac3a162cae3141e12c5f4be36ca1a6d36bcec754d02728e
        networks:
            - dev
 
    db:
        image: mysql
        container_name: db_p8_test
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_p8_test
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev
    
    www:
        build: php
        container_name: www_p8_test
        ports:
          - "8741:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev


networks:
    dev:
 
volumes:
    db-data: